INSERT INTO article (TITLE, CONTENT, CREATED_AT, UPDATED_AT) VALUES ('제목 1', '내용 1', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO ARTICLE (TITLE, CONTENT, CREATED_AT, UPDATED_AT) VALUES ('제목 2', '내용 2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO ARTICLE (TITLE, CONTENT, CREATED_AT, UPDATED_AT) VALUES ('제목 3', '내용 3', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);